env:
  - tf_version=0.11.10

sudo: required

language: bash

before_install:
  - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
  - cp .env.example .env
  - touch ~/.ssh/gableroux_aws_rsa # required file from a default value in variables
  - terraform init
  - terraform validate -backend=false # don't require aws credentials
